### ISSUE TITLE
cf push results in: "The app upload is invalid: Symlink(s) point outside of root folder"

### ISSUE THREAD

**Issue by SamwiseGambgee** [bosh-prometheus/cf_exporter#21]
Hello!
I'm trying to push 'cf_exporter' to my cf environment. 
But I get the below error:

` The app upload is invalid: Symlink(s) point outside of root folder`

Steps I followed:
`$ git clone https://github.com/bosh-prometheus/cf_exporter.git`
`$ cd cf_exporter`

Can anyone please help me to resolve this issue?

Thanks in advance!

**Comment by frodenas** [comment]
This might be related to https://github.com/cloudfoundry/cloud_controller_ng/issues/1057. As a workaround, delete the [vendor/github.com/prometheus/procfs/fixtures](https://github.com/bosh-prometheus/cf_exporter/tree/master/vendor/github.com/prometheus/procfs/fixtures) directory before pushing the app.

**Comment by SamwiseGambgee** [comment]
Thanks @frodenas for the suggestion. I was able to push the app.
Yet again, I encountered an error: 
`   2018-02-19T10:14:19.69+0530 [STG/0] OUT        **ERROR** To use go native vendoring set the $GOPACKAGENAME`
`   2018-02-19T10:14:19.69+0530 [STG/0] OUT        environment variable to your app's package name`
`   2018-02-19T10:14:19.69+0530 [STG/0] OUT        **ERROR** Unable to determine import path: GOPACKAGENAME unset`

I'm pretty new this, it might be a small thing which I maybe miss-firing. 
Can you please assist on what is going wrong?

thanks in advance!

**Comment by frodenas** [comment]
Update the [manifest.yml](https://github.com/bosh-prometheus/cf_exporter/blob/master/manifest.yml) file and add this env var: `GOPACKAGENAME: github.com/bosh-prometheus/cf_exporter`:

```yaml
---
applications:
  - name: cf-exporter
    buildpack: go_buildpack
    env:
      GOPACKAGENAME: github.com/bosh-prometheus/cf_exporter
      CF_EXPORTER_CF_API_URL: "Your Cloud Foundry API URL"
      CF_EXPORTER_CF_USERNAME: "Your Cloud Foundry Username"
      CF_EXPORTER_CF_PASSWORD: "Your Cloud Foundry Password"
```
